### Load Datasets

In [6]:
from function_06 import load_data_with_delimiters

In [8]:
file_info = [
    ("../data/raw/FIETSTELLINGEN1723-ams.csv", ';'),    
    ("../data/raw/ongevallen_2015_2020.csv", ',')      
]

dfs = load_data_with_delimiters(file_info)

df_ams = dfs[0]
df_nl = dfs[1]

print(df_ams.head())
print(df_nl.head())

   OBJECTNUMMER  Werkdag_2023  Werkdag_2022  Werkdag_2021  Werkdag_2020  \
0             1             0             0             0             0
1             2          2365          2736          1279          1764
2             3           634           673           546           442
3             4           723           716           476             0
4             5           597           532           517             0

   Werkdag_2019  Werkdag_2018  Werkdag_2017     LOCATIE  \
0           724             0           569  VRA01_0001
1          2398          2521          2187  VRA01_0002
2           590           775           547  VRA01_0003
3           388           563           359  VRA01_0004
4           466           497             0  VRA01_0005

                 WKT_LNG_LAT                WKT_LAT_LNG       LNG        LAT  \
0     POINT(5.1353 52.32418)     POINT(52.32418 5.1353)  5.135300  52.324180
1  POINT(5.023534 52.302822)  POINT(52.302822 5.023534)  5.023534  52.302822
2  POINT(5.011511 52.332756)  POINT(52.332756 5.011511)  5.011511  52.332756
3   POINT(5.01383 52.340321)   POINT(52.340321 5.01383)  5.013830  52.340321
4   POINT(4.987085 52.33948)   POINT(52.33948 4.987085)  4.987085  52.339480

   Unnamed: 13
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
                      FID  id  totaal  dodelijk  letsel  matrieel  \
0  ongevallen_2015_2020.1   1       1         0       1         0
1  ongevallen_2015_2020.2   2       1         0       0         1
2  ongevallen_2015_2020.3   3       1         0       0         1
3  ongevallen_2015_2020.4   4       1         0       1         0
4  ongevallen_2015_2020.5   5       2         0       2         0

   gdb_geomattr_data                                              shape
0                NaN  POLYGON ((179046.73279999942 309408.8781999983...
1                NaN  POLYGON ((177255.8396999985 310240.2259999998,...
2                NaN  POLYGON ((178901.10350000113 311532.4411999993...
3                NaN  POLYGON ((178656.49430000037 313910.4211000018...
4                NaN  POLYGON ((176617.4726999998 313949.6506000012,...

In [10]:
 df_ams.head()

,OBJECTNUMMER,Werkdag_2023,Werkdag_2022,Werkdag_2021,Werkdag_2020,Werkdag_2019,Werkdag_2018,Werkdag_2017,LOCATIE,WKT_LNG_LAT,WKT_LAT_LNG,LNG,LAT,Unnamed: 13
0,1,0,0,0,0,724,0,569,VRA01_0001,POINT(5.1353 52.32418),POINT(52.32418 5.1353),5.135300,52.324180,NaN
1,2,2365,2736,1279,1764,2398,2521,2187,VRA01_0002,POINT(5.023534 52.302822),POINT(52.302822 5.023534),5.023534,52.302822,NaN
2,3,634,673,546,442,590,775,547,VRA01_0003,POINT(5.011511 52.332756),POINT(52.332756 5.011511),5.011511,52.332756,NaN
3,4,723,716,476,0,388,563,359,VRA01_0004,POINT(5.01383 52.340321),POINT(52.340321 5.01383),5.013830,52.340321,NaN
4,5,597,532,517,0,466,497,0,VRA01_0005,POINT(4.987085 52.33948),POINT(52.33948 4.987085),4.987085,52.339480,NaN

In [12]:
 df_nl.head()

,FID,id,totaal,dodelijk,letsel,matrieel,gdb_geomattr_data,shape
0,ongevallen_2015_2020.1,1,1,0,1,0,NaN,POLYGON ((179046.73279999942 309408.8781999983...
1,ongevallen_2015_2020.2,2,1,0,0,1,NaN,"POLYGON ((177255.8396999985 310240.2259999998,..."
2,ongevallen_2015_2020.3,3,1,0,0,1,NaN,POLYGON ((178901.10350000113 311532.4411999993...
3,ongevallen_2015_2020.4,4,1,0,1,0,NaN,POLYGON ((178656.49430000037 313910.4211000018...
4,ongevallen_2015_2020.5,5,2,0,2,0,NaN,"POLYGON ((176617.4726999998 313949.6506000012,..."

In [ ]:
#change column name